Delivered-To: amjames2@vt.edu
Received: by 10.140.29.136 with SMTP id b8csp384567qgb;
        Tue, 18 Aug 2015 14:39:20 -0700 (PDT)
X-Received: by 10.55.31.225 with SMTP id n94mr16986499qkh.17.1439933960761;
        Tue, 18 Aug 2015 14:39:20 -0700 (PDT)
Return-Path: <noreply@github.com>
Received: from mr5.cc.vt.edu (mr5.cc.ipv6.vt.edu. [2001:468:c80:2105:0:2b8:b328:9234])
        by mx.google.com with ESMTPS id 128si33489046qhh.8.2015.08.18.14.39.20
        for <amjames2@vt.edu>
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 18 Aug 2015 14:39:20 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) client-ip=192.30.252.193;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) smtp.mailfrom=noreply@github.com;
       dkim=pass (test mode) header.i=@github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext2.iad.github.net [192.30.252.193])
	by mr5.cc.vt.edu (8.14.4/8.14.4) with ESMTP id t7ILdE2M015304
	for <amjames2@vt.edu>; Tue, 18 Aug 2015 17:39:19 -0400
Date: Tue, 18 Aug 2015 14:39:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1439933954;
	bh=pDwILg5kur3Xb9FH9qAdVXDaG47YLJFg9cshuzKbkds=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=vi6QxabPzQ3ehkGD7X02n8E/dh3IzMaCnulLTXOmd8yx0ZqhD71eQBp0BOkewMlyt
	 fEsW+oRNPkY3+kqCtvu5UDWUzouVSEaMdxZ0o9/pZTCMR5hLULAaH/NV0lL5DHJr9F
	 On66vu0XSoBH/lG0vDIDkNolc3+jfeJ7oLgok6wM=
From: fevangelista <notifications@github.com>
Reply-To: psi4/psi4public <reply+0089f6429c5929ae859c4c0da6cfa2b8e78b30b597ae967e92cf0000000111eb680292a169ce0610a822@reply.github.com>
To: psi4/psi4public <psi4public@noreply.github.com>
Message-ID: <psi4/psi4public/issues/169@github.com>
Subject: [psi4public] User-defined basis set broken? (#169)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_55d3a6028a4bf_32383fef998412a08375a";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: fevangelista
X-GitHub-Recipient: amjames
List-ID: psi4/psi4public <psi4public.psi4.github.com>
List-Archive: https://github.com/psi4/psi4public
List-Post: <mailto:reply+0089f6429c5929ae859c4c0da6cfa2b8e78b30b597ae967e92cf0000000111eb680292a169ce0610a822@reply.github.com>
List-Unsubscribe: <mailto:unsub+0089f6429c5929ae859c4c0da6cfa2b8e78b30b597ae967e92cf0000000111eb680292a169ce0610a822@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AIn2Qu2Olrh9oeqloshGjG5CecwsjZKRks5oo52CgaJpZM4Ft7IL>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: amjames2@vt.edu
X-Spam-Status: No, score=-4.4 required=5.0 tests=DKIM_SIGNED,DKIM_VALID,
	DKIM_VALID_AU,HTML_IMAGE_ONLY_20,HTML_MESSAGE,RCVD_IN_DNSWL_HI
	autolearn=disabled version=3.3.1
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on mr5.cc.vt.edu
X-Gm-Spam: 0
X-Gm-Phishy: 0
X-Gm-Spam: 0
X-Gm-Phishy: 0


----==_mimepart_55d3a6028a4bf_32383fef998412a08375a
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

The following input file fails with the following message:

```
Traceback (most recent call last):
  File "/Users/francesco/Source/psi4/lib/python/inputparser.py", line 732, in process_input
    temp = re.sub('^from __future__ import .*$', future_replace, temp, flags=re.MULTILINE)
TypeError: sub() got an unexpected keyword argument 'flags'
```

I was wondering: is it possible that recent changes to python affect the ability to read user-defined basis sets from input files?

```
molecule h2o {
0 1
O
H 1 1.0
H 1 1.0 2 104.5
}

basis {
cartesian
H 0
S 3 1.00
      3.42525091 0.15432897
      0.62391373 0.53532814
      0.16885540 0.44463454
****
O 0
S 3 1.00
    130.7093200 0.15432897
     23.8088610 0.53532814
      6.4436083 0.44463454
SP 3 1.00
      5.0331513 -0.09996723 0.15591627
      1.1695961 0.39951283 0.60768372
      0.3803890 0.70011547 0.39195739
****
}

energy('scf')
```

---
Reply to this email directly or view it on GitHub:
https://github.com/psi4/psi4public/issues/169
----==_mimepart_55d3a6028a4bf_32383fef998412a08375a
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>The following input file fails with the following message:</p>

<pre><code>Traceback (most recent call last):
  File "/Users/francesco/Source/psi4/lib/python/inputparser.py", line 732, in process_input
    temp = re.sub('^from __future__ import .*$', future_replace, temp, flags=re.MULTILINE)
TypeError: sub() got an unexpected keyword argument 'flags'
</code></pre>

<p>I was wondering: is it possible that recent changes to python affect the ability to read user-defined basis sets from input files?</p>

<pre><code>molecule h2o {
0 1
O
H 1 1.0
H 1 1.0 2 104.5
}

basis {
cartesian
H 0
S 3 1.00
      3.42525091 0.15432897
      0.62391373 0.53532814
      0.16885540 0.44463454
****
O 0
S 3 1.00
    130.7093200 0.15432897
     23.8088610 0.53532814
      6.4436083 0.44463454
SP 3 1.00
      5.0331513 -0.09996723 0.15591627
      1.1695961 0.39951283 0.60768372
      0.3803890 0.70011547 0.39195739
****
}

energy('scf')
</code></pre>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/psi4/psi4public/issues/169">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/AIn2Qj86zz2Ztqz-YmlJYfdwQ7wBnISmks5oo52CgaJpZM4Ft7IL.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/psi4/psi4public/issues/169"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_55d3a6028a4bf_32383fef998412a08375a--
